// src/generator.ts — turns a RepoContext into an AGENTS.md markdown string
import type { RepoContext } from "./scanner";

const REVIEW_COMMENT =
  "<!-- review before committing — auto-generated by agents-md-gen -->";

/** Map script key names to human-readable labels for the Commands section. */
const SCRIPT_LABELS: Record<string, string> = {
  start: "Run",
  dev: "Dev server",
  test: "Test",
  build: "Build",
  lint: "Lint",
  format: "Format",
  typecheck: "Type-check",
  "type-check": "Type-check",
  check: "Check",
  clean: "Clean",
  deploy: "Deploy",
};

/** Human-readable labels for well-known layout directories. */
const DIR_LABELS: Record<string, string> = {
  src: "main source tree",
  lib: "compiled/library output",
  packages: "monorepo packages",
  apps: "monorepo apps",
  bin: "CLI entrypoints",
  cli: "CLI entrypoints",
  tests: "test suite",
  test: "test suite",
  docs: "documentation",
};

function section(header: string, body: string): string {
  return `## ${header}\n${REVIEW_COMMENT}\n${body}\n`;
}

function projectOverview(ctx: RepoContext): string {
  const name = ctx.name || "(unnamed)";
  const description = ctx.description || "(no description)";
  const language = ctx.language !== "unknown" ? ctx.language : "(unknown)";
  const runtime = ctx.runtime !== "unknown" ? ctx.runtime : "(unknown)";
  const version = ctx.version || "0.0.0";

  const lines: string[] = [
    `**Name:** ${name}`,
    `**Version:** ${version}`,
    `**Description:** ${description}`,
    `**Language:** ${language}`,
    `**Runtime:** ${runtime}`,
  ];

  if (ctx.hasTsConfig) {
    lines.push("**TypeScript config:** tsconfig.json present");
  }

  if (ctx.readmeSummary) {
    lines.push("", "**README excerpt:**", `> ${ctx.readmeSummary.replace(/\n/g, " ").slice(0, 300)}`);
  }

  return section("Project Overview", lines.join("\n"));
}

function commands(ctx: RepoContext): string {
  const entries = Object.entries(ctx.scripts);

  if (entries.length === 0) {
    return section("Commands", "_No scripts defined in package.json._");
  }

  const lines: string[] = [];
  for (const [key, cmd] of entries) {
    const label = SCRIPT_LABELS[key] ?? key;
    const invokeAs =
      ctx.runtime === "bun"
        ? `bun run ${key}`
        : `npm run ${key}`;
    lines.push(`- **${label}** (\`${invokeAs}\`): \`${cmd}\``);
  }

  return section("Commands", lines.join("\n"));
}

function architecture(ctx: RepoContext): string {
  const lines: string[] = [];

  // Directory layout
  if (ctx.dirs.length > 0) {
    for (const d of ctx.dirs) {
      const label = DIR_LABELS[d] ?? d;
      lines.push(`- **${capitalise(label)}:** \`${d}/\``);
    }
  } else {
    lines.push("_No standard directories detected._");
  }

  // Entry point (from package.json main/module)
  if (ctx.entryPoint) {
    lines.push(`- **Entry point:** \`${ctx.entryPoint}\` (from package.json \`main\`)`);
  }

  // CLI bin entries
  const binItems = Object.entries(ctx.binEntries);
  if (binItems.length === 1) {
    const [, binPath] = binItems[0];
    lines.push(`- **CLI:** \`${binPath}\` (from package.json \`bin\`)`);
  } else if (binItems.length > 1) {
    for (const [binName, binPath] of binItems) {
      lines.push(`- **CLI (\`${binName}\`):** \`${binPath}\` (from package.json \`bin\`)`);
    }
  }

  return section("Architecture", lines.join("\n"));
}

function capitalise(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function keyConventions(ctx: RepoContext): string {
  const lines: string[] = [];

  if (ctx.language === "typescript") {
    lines.push("- Use TypeScript throughout; keep types explicit.");
    if (ctx.hasTsConfig) {
      lines.push("- tsconfig.json is present — respect its compiler options.");
    }
  } else if (ctx.language === "javascript") {
    lines.push("- Project uses JavaScript (no TypeScript compilation step).");
  } else {
    lines.push("- Language not detected — check package.json devDependencies.");
  }

  if (ctx.runtime === "bun") {
    lines.push("- Use `bun` / `bunx` — never `npm` / `npx`.");
    lines.push("- Prefer Bun-native APIs (e.g. `Bun.file`, `bun:test`) over Node equivalents.");
  } else if (ctx.runtime === "node") {
    lines.push("- Runtime is Node.js; use `node` / `npx` as appropriate.");
  } else {
    lines.push("- Runtime not detected — check scripts in package.json.");
  }

  if (ctx.existingAgentContext) {
    lines.push("", "**Existing CLAUDE.md context (excerpt):**");
    const excerpt = ctx.existingAgentContext.slice(0, 400).replace(/\n/g, "\n> ");
    lines.push(`> ${excerpt}`);
  }

  if (lines.length === 0) {
    lines.push("_No conventions detected. Populate manually._");
  }

  return section("Key Conventions", lines.join("\n"));
}

function agentNotes(ctx: RepoContext): string {
  const lines: string[] = [
    "This file was auto-generated by **agents-md-gen**.",
    "",
    "- Review every section before committing — generated content may be incomplete or wrong.",
    "- Update `## Key Conventions` with project-specific rules that agents must follow.",
    "- Update `## Architecture` if the project layout changes significantly.",
    "- Re-run the generator after major structural changes to refresh this scaffold.",
  ];

  if (ctx.name) {
    lines.push(`- Project: \`${ctx.name}\` v${ctx.version ?? "0.0.0"}`);
  }

  return section("Agent Notes", lines.join("\n"));
}

/**
 * Generates an AGENTS.md markdown string from a scanned RepoContext.
 * Each section starts with an inline review-reminder HTML comment.
 * Falls back gracefully when context fields are empty or missing.
 */
export function generateAgentsMd(context: RepoContext): string {
  const sections = [
    projectOverview(context),
    commands(context),
    architecture(context),
    keyConventions(context),
    agentNotes(context),
  ];

  return `# AGENTS.md\n\n${sections.join("\n")}`;
}
