import { describe, expect, it } from "bun:test";
import { generateAgentsMd } from "./generator";
import type { RepoContext } from "./types";

const AUTO_GEN_COMMENT = "<!-- review before committing — auto-generated by agents-md-gen -->";

function makeCtx(overrides: Partial<RepoContext> = {}): RepoContext {
  return {
    name: "my-cool-project",
    description: "A demo project for testing",
    language: "TypeScript",
    runtime: "bun",
    scripts: {
      test: "bun test",
      build: "bun run build.ts",
      lint: "bunx eslint src",
      start: "bun src/index.ts",
    },
    srcFiles: ["index.ts", "scanner.ts", "generator.ts", "types.ts"],
    hasClaudeMd: false,
    existingAgentContext: "",
    ...overrides,
  };
}

describe("generateAgentsMd", () => {
  it("starts with # AGENTS.md heading", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out.trimStart()).toMatch(/^# AGENTS\.md/);
  });

  it("includes ## Project Overview section", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain("## Project Overview");
  });

  it("includes repo name in Project Overview", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain("my-cool-project");
  });

  it("includes description in Project Overview", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain("A demo project for testing");
  });

  it("includes detected language in Project Overview", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain("TypeScript");
  });

  it("includes detected runtime in Project Overview", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain("bun");
  });

  it("includes ## Commands section", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain("## Commands");
  });

  it("populates commands from scripts", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain("bun test");
    expect(out).toContain("bun run build.ts");
    expect(out).toContain("bunx eslint src");
  });

  it("labels commands by script name", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toMatch(/test[:\s]/i);
    expect(out).toMatch(/build[:\s]/i);
    expect(out).toMatch(/lint[:\s]/i);
  });

  it("includes ## Architecture section", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain("## Architecture");
  });

  it("lists src/ files in Architecture", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain("index.ts");
    expect(out).toContain("scanner.ts");
    expect(out).toContain("generator.ts");
  });

  it("includes existing agent context when present", () => {
    const ctx = makeCtx({ existingAgentContext: "## My Custom Rule\nAlways use bun." });
    const out = generateAgentsMd(ctx);
    expect(out).toContain("## My Custom Rule");
    expect(out).toContain("Always use bun.");
  });

  it("includes ## Key Conventions section", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain("## Key Conventions");
  });

  it("includes ## Agent Notes section", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain("## Agent Notes");
  });

  it("includes auto-gen comment at least once", () => {
    const out = generateAgentsMd(makeCtx());
    expect(out).toContain(AUTO_GEN_COMMENT);
  });

  it("includes auto-gen comment on Key Conventions section", () => {
    const out = generateAgentsMd(makeCtx());
    const keyConvIndex = out.indexOf("## Key Conventions");
    const commentAfter = out.indexOf(AUTO_GEN_COMMENT, keyConvIndex);
    const nextSectionAfter = out.indexOf("\n## ", keyConvIndex + 1);
    // Comment must appear between Key Conventions and the next section (or end)
    expect(commentAfter).toBeGreaterThan(keyConvIndex);
    if (nextSectionAfter !== -1) {
      expect(commentAfter).toBeLessThan(nextSectionAfter);
    }
  });

  it("includes auto-gen comment on Agent Notes section", () => {
    const out = generateAgentsMd(makeCtx());
    const agentNotesIndex = out.indexOf("## Agent Notes");
    const commentAfter = out.indexOf(AUTO_GEN_COMMENT, agentNotesIndex);
    expect(commentAfter).toBeGreaterThan(agentNotesIndex);
  });

  it("handles empty scripts gracefully", () => {
    const out = generateAgentsMd(makeCtx({ scripts: {} }));
    expect(out).toContain("## Commands");
    // Should not throw; section present but no commands listed
  });

  it("handles empty srcFiles gracefully", () => {
    const out = generateAgentsMd(makeCtx({ srcFiles: [] }));
    expect(out).toContain("## Architecture");
  });

  it("sections appear in correct order", () => {
    const out = generateAgentsMd(makeCtx());
    const positions = [
      out.indexOf("# AGENTS.md"),
      out.indexOf("## Project Overview"),
      out.indexOf("## Commands"),
      out.indexOf("## Architecture"),
      out.indexOf("## Key Conventions"),
      out.indexOf("## Agent Notes"),
    ];
    for (let i = 0; i < positions.length - 1; i++) {
      expect(positions[i]).toBeLessThan(positions[i + 1]);
    }
  });
});
