// src/generator.test.ts
import { test, expect, describe } from "bun:test";
import { generateAgentsMd } from "./generator";
import type { RepoContext } from "./scanner";

const REVIEW_COMMENT = "<!-- review before committing — auto-generated by agents-md-gen -->";

const fullContext: RepoContext = {
  name: "my-app",
  description: "A test application",
  version: "1.2.3",
  language: "typescript",
  runtime: "bun",
  scripts: {
    start: "bun run src/index.ts",
    test: "bun test",
    build: "tsc",
    lint: "eslint src",
  },
  devDependencies: ["typescript", "@types/node", "eslint"],
  srcFiles: ["index.ts", "utils.ts", "types.ts"],
  readmeSummary: "My App is a great project.",
  existingAgentContext: "# Agent Context\nUse bun.",
  hasTsConfig: true,
  dirs: ["src", "tests", "docs"],
  entryPoint: "src/index.ts",
  binEntries: { "my-cli": "bin/cli.ts" },
};

const minimalContext: RepoContext = {
  name: "",
  description: "",
  version: "0.0.0",
  language: "unknown",
  runtime: "unknown",
  scripts: {},
  devDependencies: [],
  srcFiles: [],
  readmeSummary: "",
  existingAgentContext: null,
  hasTsConfig: false,
  dirs: [],
  entryPoint: undefined,
  binEntries: {},
};

describe("generateAgentsMd — section headers", () => {
  test("output contains ## Project Overview", () => {
    const md = generateAgentsMd(fullContext);
    expect(md).toContain("## Project Overview");
  });

  test("output contains ## Commands", () => {
    const md = generateAgentsMd(fullContext);
    expect(md).toContain("## Commands");
  });

  test("output contains ## Architecture", () => {
    const md = generateAgentsMd(fullContext);
    expect(md).toContain("## Architecture");
  });

  test("output contains ## Key Conventions", () => {
    const md = generateAgentsMd(fullContext);
    expect(md).toContain("## Key Conventions");
  });

  test("output contains ## Agent Notes", () => {
    const md = generateAgentsMd(fullContext);
    expect(md).toContain("## Agent Notes");
  });

  test("sections appear in the correct order", () => {
    const md = generateAgentsMd(fullContext);
    const overviewIdx = md.indexOf("## Project Overview");
    const commandsIdx = md.indexOf("## Commands");
    const archIdx = md.indexOf("## Architecture");
    const conventionsIdx = md.indexOf("## Key Conventions");
    const notesIdx = md.indexOf("## Agent Notes");
    expect(overviewIdx).toBeLessThan(commandsIdx);
    expect(commandsIdx).toBeLessThan(archIdx);
    expect(archIdx).toBeLessThan(conventionsIdx);
    expect(conventionsIdx).toBeLessThan(notesIdx);
  });
});

describe("generateAgentsMd — inline review comment", () => {
  test("Project Overview section contains the review comment", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Project Overview");
    const end = md.indexOf("## Commands");
    expect(md.slice(start, end)).toContain(REVIEW_COMMENT);
  });

  test("Commands section contains the review comment", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Commands");
    const end = md.indexOf("## Architecture");
    expect(md.slice(start, end)).toContain(REVIEW_COMMENT);
  });

  test("Architecture section contains the review comment", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Architecture");
    const end = md.indexOf("## Key Conventions");
    expect(md.slice(start, end)).toContain(REVIEW_COMMENT);
  });

  test("Key Conventions section contains the review comment", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Key Conventions");
    const end = md.indexOf("## Agent Notes");
    expect(md.slice(start, end)).toContain(REVIEW_COMMENT);
  });

  test("Agent Notes section contains the review comment", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Agent Notes");
    expect(md.slice(start)).toContain(REVIEW_COMMENT);
  });
});

describe("generateAgentsMd — Commands section content", () => {
  test("includes run/start command from scripts", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Commands");
    const end = md.indexOf("## Architecture");
    const section = md.slice(start, end);
    expect(section).toContain("bun run src/index.ts");
  });

  test("includes test command from scripts", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Commands");
    const end = md.indexOf("## Architecture");
    const section = md.slice(start, end);
    expect(section).toContain("bun test");
  });

  test("includes build command from scripts", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Commands");
    const end = md.indexOf("## Architecture");
    const section = md.slice(start, end);
    expect(section).toContain("tsc");
  });

  test("includes lint command from scripts", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Commands");
    const end = md.indexOf("## Architecture");
    const section = md.slice(start, end);
    expect(section).toContain("eslint src");
  });
});

describe("generateAgentsMd — minimal/empty repo fallback", () => {
  test("does not crash on minimal context", () => {
    expect(() => generateAgentsMd(minimalContext)).not.toThrow();
  });

  test("still contains all 5 section headers with minimal context", () => {
    const md = generateAgentsMd(minimalContext);
    expect(md).toContain("## Project Overview");
    expect(md).toContain("## Commands");
    expect(md).toContain("## Architecture");
    expect(md).toContain("## Key Conventions");
    expect(md).toContain("## Agent Notes");
  });

  test("still contains review comment in all sections with minimal context", () => {
    const md = generateAgentsMd(minimalContext);
    expect(md.split(REVIEW_COMMENT).length - 1).toBeGreaterThanOrEqual(5);
  });

  test("returns a non-empty string for minimal context", () => {
    const md = generateAgentsMd(minimalContext);
    expect(md.length).toBeGreaterThan(0);
  });
});

describe("generateAgentsMd — Project Overview content", () => {
  test("includes project name", () => {
    const md = generateAgentsMd(fullContext);
    expect(md).toContain("my-app");
  });

  test("includes description", () => {
    const md = generateAgentsMd(fullContext);
    expect(md).toContain("A test application");
  });

  test("includes language", () => {
    const md = generateAgentsMd(fullContext);
    expect(md).toContain("typescript");
  });
});

describe("generateAgentsMd — Architecture section: directory layout", () => {
  test("lists detected directories as bullets", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Architecture");
    const end = md.indexOf("## Key Conventions");
    const archSection = md.slice(start, end);
    expect(archSection).toContain("`src/`");
    expect(archSection).toContain("`tests/`");
    expect(archSection).toContain("`docs/`");
  });

  test("includes human-readable label for src/", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Architecture");
    const end = md.indexOf("## Key Conventions");
    const archSection = md.slice(start, end);
    expect(archSection).toContain("Main source tree");
  });

  test("includes human-readable label for tests/", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Architecture");
    const end = md.indexOf("## Key Conventions");
    const archSection = md.slice(start, end);
    expect(archSection).toContain("Test suite");
  });

  test("shows fallback when no dirs detected", () => {
    const md = generateAgentsMd(minimalContext);
    const start = md.indexOf("## Architecture");
    const end = md.indexOf("## Key Conventions");
    const archSection = md.slice(start, end);
    expect(archSection).toContain("No standard directories detected");
  });
});

describe("generateAgentsMd — Architecture section: entry point", () => {
  test("shows entry point when present", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Architecture");
    const end = md.indexOf("## Key Conventions");
    const archSection = md.slice(start, end);
    expect(archSection).toContain("`src/index.ts`");
    expect(archSection).toContain("Entry point");
  });

  test("omits entry point line when not set", () => {
    const md = generateAgentsMd(minimalContext);
    const start = md.indexOf("## Architecture");
    const end = md.indexOf("## Key Conventions");
    const archSection = md.slice(start, end);
    expect(archSection).not.toContain("Entry point");
  });

  test("entry point references package.json main field", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Architecture");
    const end = md.indexOf("## Key Conventions");
    const archSection = md.slice(start, end);
    expect(archSection).toContain("package.json");
    expect(archSection).toContain("main");
  });
});

describe("generateAgentsMd — Architecture section: bin entries", () => {
  test("shows CLI bin path when single entry", () => {
    const md = generateAgentsMd(fullContext);
    const start = md.indexOf("## Architecture");
    const end = md.indexOf("## Key Conventions");
    const archSection = md.slice(start, end);
    expect(archSection).toContain("`bin/cli.ts`");
    expect(archSection).toContain("CLI");
  });

  test("omits CLI line when no bin entries", () => {
    const md = generateAgentsMd(minimalContext);
    const start = md.indexOf("## Architecture");
    const end = md.indexOf("## Key Conventions");
    const archSection = md.slice(start, end);
    expect(archSection).not.toContain("CLI");
  });

  test("shows bin name for multiple CLI entries", () => {
    const ctx: RepoContext = {
      ...minimalContext,
      binEntries: { foo: "bin/foo.ts", bar: "bin/bar.ts" },
    };
    const md = generateAgentsMd(ctx);
    const start = md.indexOf("## Architecture");
    const end = md.indexOf("## Key Conventions");
    const archSection = md.slice(start, end);
    expect(archSection).toContain("`foo`");
    expect(archSection).toContain("`bar`");
    expect(archSection).toContain("`bin/foo.ts`");
    expect(archSection).toContain("`bin/bar.ts`");
  });
});
