import type { RepoContext } from "./types";

const AUTO_GEN_COMMENT =
  "<!-- review before committing — auto-generated by agents-md-gen -->";

/**
 * Generate a ready-to-use AGENTS.md scaffold from a RepoContext.
 */
export function generateAgentsMd(ctx: RepoContext): string {
  const sections: string[] = [];

  // ── Heading ──────────────────────────────────────────────────────────────
  sections.push(`# AGENTS.md\n${AUTO_GEN_COMMENT}`);

  // ── Project Overview ─────────────────────────────────────────────────────
  const overview = [
    `## Project Overview`,
    ``,
    `- **Name:** ${ctx.name}`,
    `- **Description:** ${ctx.description || "_No description provided._"}`,
    `- **Language:** ${ctx.language}`,
    `- **Runtime:** ${ctx.runtime}`,
  ].join("\n");
  sections.push(overview);

  // ── Commands ─────────────────────────────────────────────────────────────
  const commandLines: string[] = [`## Commands`, ``];
  const scriptEntries = Object.entries(ctx.scripts);
  if (scriptEntries.length === 0) {
    commandLines.push("_No scripts found in package.json._");
  } else {
    for (const [name, cmd] of scriptEntries) {
      commandLines.push(`- **${name}:** \`${cmd}\``);
    }
  }
  sections.push(commandLines.join("\n"));

  // ── Architecture ─────────────────────────────────────────────────────────
  const archLines: string[] = [`## Architecture`, ``];

  if (ctx.srcFiles.length > 0) {
    archLines.push(`### src/ files`, ``);
    for (const f of ctx.srcFiles) {
      archLines.push(`- \`${f}\``);
    }
  } else {
    archLines.push("_No src/ files detected._");
  }

  if (ctx.existingAgentContext) {
    archLines.push(``);
    archLines.push(`### Notes from ${ctx.hasClaudeMd ? "CLAUDE.md" : "AGENTS.md"}`, ``);
    archLines.push(ctx.existingAgentContext.trimEnd());
  }

  sections.push(archLines.join("\n"));

  // ── Key Conventions ───────────────────────────────────────────────────────
  sections.push(
    [
      `## Key Conventions`,
      ``,
      AUTO_GEN_COMMENT,
      ``,
      `_Add project-specific conventions here (naming, patterns, forbidden actions)._`,
    ].join("\n")
  );

  // ── Agent Notes ───────────────────────────────────────────────────────────
  sections.push(
    [
      `## Agent Notes`,
      ``,
      AUTO_GEN_COMMENT,
      ``,
      `_Add notes for AI agents working in this repo (gotchas, important files, workflow tips)._`,
    ].join("\n")
  );

  return sections.join("\n\n") + "\n";
}
